fixed pipe name; updated example
rizinorg/rz-pipe pull request #26
Opened 2021-09-13 06:13 UTC by ctlayon

The in/out pipe for golang was incorrect; also updated the example to make it work out of the box.

2021-09-13 08:50 UTC, wargio approved these changes

2021-09-13 16:05 UTC, XVilka requested changes

2021-09-13 16:05 UTC, XVilka commented on go/example/example.go
> +	r2p, err := rzpipe.NewPipe(path)
`rzp` please.

2021-09-14 01:27 UTC, ctlayon commented on go/example/example.go
> +	r2p, err := rzpipe.NewPipe(path)
Good catch, updated.

2021-09-14 07:09 UTC, XVilka approved these changes

2021-09-14 08:01 UTC, merged